controllers:
  - name: DynamicGapPlannerROS
    type: dynamic_gap/DynamicGapPlannerROS

controller_frequency: 5.0
controller_patience: 15.0
planner_frequency: 0.0

DynamicGapPlannerROS:
  holonomic: true   # planning information
  projection_operator: true
  egocircle_prop_cheat: false
  gap_feasibility_check: true
  perfect_gap_models: false
  future_scan_propagation: true

  # manual control
  man_ctrl: false

  # goal param
  xy_goal_tolerance: 0.25
  yaw_goal_tolerance: 6.28

  # gap association
  assoc_thresh: 0.50

  # gap manipulation
  epsilon1: 0.20
  epsilon2: 0.30
  radial_extend: true

  # trajectory
  integrate_maxt: 5.0
  integrate_stept: 0.5
  inf_ratio: 1.21

  # control
  k_fb_x: 1.5
  k_fb_y: 1.5
  k_fb_theta: 1.5
  ctrl_ahead_pose: 2

  # projection params
  k_po_x: 1.0
  k_po_theta: 1.0

  r_unity: 0.35
  r_zero: 1.0